defaults:
  - hydra: hydra_simple
  - _self_


name: CookingZoo
separate_controllers: false

logger:
  load_dir: ${name}
  log_grad: false
  project: DiversityGeneration
  entity: gingerninja
  logger_period: 0.0000001
  save_model: true
  save_model_period: 5
  store_video: true

# # Data collection-related parameters
# matrix-game-no-state-v0

env_eval:
  eps_per_interaction: 10

env:
  name: n-agent-rps-v0
  parallel:
    adhoc_collection: 16
    eval: 8

run:
  use_cuda: false
  num_timesteps: 1600000
  num_eval_episodes: 10
  seed: 0
  eval_seed: 500
  total_checkpoints: 50
  load_from_checkpoint: -1
  device_id: 3
  load: true
  model_load_dir: /scratch/cluster/arrasy/outputs/CookingZoo/2024-12-29/08-16-15/models
  model_id: 50

populations:
  num_populations: 3
  num_agents_per_population: 3

train:
  method: L-BRDiv
  timesteps_per_update: 4
  gamma: 0.99
  target_update_rate: 1e-3
  lagrange_lr: 0.05
  lr: 0.0001
  max_grad_norm: 1.0
  epochs_per_update: 4
  eps_clip: 0.2
  dual_clip: 3.0
  lagrange_update_period: 10
  with_dual_clip: false
  with_open_ended_learning: true
  init_lagrange: 0
  tolerance_factor: 0.5

loss_weights:
  critic_loss_weight: 1.0
  actor_loss_weight: 1.0
  entropy_regularizer_loss_weight: 0.001

model:
  actor_dims:
    - 64
    - 64
  critic_dims:
    - 64
    - 64
  agent_rep_size: 32
  enc_dims:
    - 64
    - 64
    - 64
  init_ortho: false
