defaults:
  - hydra: hydra_simple
  - _self_


name: CookingZoo
separate_controllers: false

logger:
  load_dir: ${name}
  log_grad: false
  project: DiversityGeneration
  entity: gingerninja
  logger_period: 0.1
  save_model: true
  save_model_period: 5
  store_video: true

# # Data collection-related parameters
# matrix-game-no-state-v0
env:
  name: rps-v0
  parallel:
    sp_collection: 4
    xp_collection: 12
    eval: 6

run:
  use_cuda: false
  num_timesteps: 800000
  num_eval_episodes: 1
  seed: 0
  eval_seed: 500
  total_checkpoints: 50
  load_from_checkpoint: -1
  device_id: 3

populations:
  num_populations: 3
  num_agents_per_population: 2

train:
  method: L-BRDiv
  timesteps_per_update: 4
  gamma: 0.95
  target_update_rate: 1e-3
  lr: 0.0001
  max_grad_norm: 1.0
  epochs_per_update: 4
  eps_clip: 0.2
  init_lagrange: 10.0
  dual_clip: 3.0
  lagrange_update_period: 10
  with_dual_clip: false
  anneal_end: 0.5
  lagrange_lr: 0.05
  tolerance_factor: 0.7

loss_weights:
  sp_val_loss_weight: 5.0
  xp_val_loss_weight: 5.0
  entropy_regularizer_loss: 0.0005
  lagrange_weights: 1

model:
  actor_dims:
    - 64
    - 64
  critic_dims:
    - 64
    - 64
  init_ortho: false
