defaults:
  - hydra: hydra_simple
  - _self_


name: CookingZoo
separate_controllers: false

logger:
  load_dir: ${name}
  log_grad: false
  project: DiversityGeneration
  entity: gingerninja
  logger_period: 0.1
  save_model: true
  save_model_period: 5

# # Data collection-related parameters
env:
  name: matrix-game-no-state-v0
  parallel:
    sp_collection: 40
    xp_collection: 0
    eval: 6

run:
  use_cuda: false
  num_timesteps: 12000000
  num_eval_episodes: 1
  seed: 0
  eval_seed: 500
  total_checkpoints: 50
  load_from_checkpoint: -1
  device_id: 2

populations:
  num_populations: 2

train:
  method: FCP
  timesteps_per_update: 4
  gamma: 0.99
  target_update_rate: 1e-3
  lr: 1e-3
  max_grad_norm: 1.0
  epochs_per_update: 10
  eps_clip: 0.2
  dual_clip: 3.0
  with_dual_clip: false

loss_weights:
  sp_val_loss_weight: 1.0
  xp_loss_weights: 0.0 
  entropy_regularizer_loss: 0.001
  
model:
  actor_dims:
    - 32
    - 32
  critic_dims:
    - 32
    - 32
  init_ortho: false
